### ISSUE TITLE
Ability to have pages without sidebar item

### ISSUE THREAD

**Issue by rmehta** [frappe/wiki#226]
The goal is to have pages which do not show up in the sidebar (for example ERPNext docs sidebar is too long)

1. Create a new options "Page settings"

<img width="402" alt="Screenshot 2024-04-16 at 10 44 44 AM" src="https://github.com/frappe/wiki/assets/140076/d540ec17-5b4b-453c-a572-12e2fe51a27e">

2. In a modal, show options for:
   - Show in sidebar
   - Route (this should also be editable)

**Comment by pushkarjsh88** [comment]
Let me explain the problem with an example. 

-The aim is to reduce the pages listed on the sidebar and make it more organised. 
-So, instead of having a list of 18 pages under 'Roles and Permissions' we are grouping relevant pages under 'Role' and 'Permissions' separately. 
-Separate Wiki pages have been created for these two groups which are added to the Wiki Space.
-These two group pages contain links to the other relevant pages which were earlier listed in the NavBar and to be removed from there.
-Now, if we remove those pages from the NavBar / Wiki Space they will not be accessible from the newly created 'Role' and 'Permissions' pages because there is a validation that all pages should be directly linked to a Wiki Space to get displayed.
