### ISSUE TITLE
show username/name instead of email in revisions

### ISSUE THREAD

**Issue by ankush** [frappe/wiki#45]
reason: privacy?

<img width="405" alt="Screenshot 2021-11-08 at 7 18 14 PM" src="https://user-images.githubusercontent.com/9079960/140753283-79bc8917-9307-4c06-9608-669ee8f8670c.png">

**Comment by ruchamahabal** [comment]
This is fixed in revisions:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/24353136/229067926-ec677416-401a-4311-9c53-5f332407d794.png">

But new pages created still show the email:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/24353136/229068284-453309fc-baab-45ee-a074-4469868cdeb9.png">

https://frappehr.com/docs/v14/user/manual/en/human-resources/goal/revisions
